USE [master]
GO
/****** Object:  Database [DbLibrary]    Script Date: 22/06/2020 16:16:32 ******/
CREATE DATABASE [DbLibrary]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DbLibrary', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DbLibrary.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DbLibrary_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DbLibrary_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [DbLibrary] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DbLibrary].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DbLibrary] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DbLibrary] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DbLibrary] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DbLibrary] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DbLibrary] SET ARITHABORT OFF 
GO
ALTER DATABASE [DbLibrary] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DbLibrary] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DbLibrary] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DbLibrary] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DbLibrary] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DbLibrary] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DbLibrary] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DbLibrary] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DbLibrary] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DbLibrary] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DbLibrary] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DbLibrary] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DbLibrary] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DbLibrary] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DbLibrary] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DbLibrary] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DbLibrary] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DbLibrary] SET RECOVERY FULL 
GO
ALTER DATABASE [DbLibrary] SET  MULTI_USER 
GO
ALTER DATABASE [DbLibrary] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DbLibrary] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DbLibrary] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DbLibrary] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DbLibrary] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'DbLibrary', N'ON'
GO
ALTER DATABASE [DbLibrary] SET QUERY_STORE = OFF
GO
USE [DbLibrary]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 22/06/2020 16:16:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Author]    Script Date: 22/06/2020 16:16:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Author](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[Birthdate] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Author] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Book]    Script Date: 22/06/2020 16:16:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Book](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[title] [nvarchar](50) NOT NULL,
	[ISBN] [nvarchar](50) NOT NULL,
	[Authorid] [int] NOT NULL,
	[Categoryid] [int] NOT NULL,
 CONSTRAINT [PK_Book] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Category]    Script Date: 22/06/2020 16:16:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Category](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](500) NOT NULL,
 CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20200618033942_InitialMigration', N'2.2.6-servicing-10079')
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20200618040825_1MigrationRequiredAndLength', N'2.2.6-servicing-10079')
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20200618182821_2MigrationBaseEntity', N'2.2.6-servicing-10079')
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20200620005203_2MigrationIds', N'2.2.6-servicing-10079')
GO
SET IDENTITY_INSERT [dbo].[Author] ON 
GO
INSERT [dbo].[Author] ([id], [Name], [LastName], [Birthdate]) VALUES (1006, N'Gabriel', N'Garcia Marquez', CAST(N'1927-03-06T00:00:00.0000000' AS DateTime2))
GO
SET IDENTITY_INSERT [dbo].[Author] OFF
GO
SET IDENTITY_INSERT [dbo].[Book] ON 
GO
INSERT [dbo].[Book] ([id], [title], [ISBN], [Authorid], [Categoryid]) VALUES (2010, N'Cien Años de Soledad', N'ISBN1', 1006, 1)
GO
SET IDENTITY_INSERT [dbo].[Book] OFF
GO
SET IDENTITY_INSERT [dbo].[Category] ON 
GO
INSERT [dbo].[Category] ([id], [Name], [Description]) VALUES (1, N'Novela', N'descripcion de la novela prueba')
GO
INSERT [dbo].[Category] ([id], [Name], [Description]) VALUES (2, N'Terror', N'textos literarios que producen miedo en el lector')
GO
SET IDENTITY_INSERT [dbo].[Category] OFF
GO
/****** Object:  Index [IX_Book_Authorid]    Script Date: 22/06/2020 16:16:32 ******/
CREATE NONCLUSTERED INDEX [IX_Book_Authorid] ON [dbo].[Book]
(
	[Authorid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Book_Categoryid]    Script Date: 22/06/2020 16:16:32 ******/
CREATE NONCLUSTERED INDEX [IX_Book_Categoryid] ON [dbo].[Book]
(
	[Categoryid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Book]  WITH CHECK ADD  CONSTRAINT [FK_Book_Author_Authorid] FOREIGN KEY([Authorid])
REFERENCES [dbo].[Author] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Book] CHECK CONSTRAINT [FK_Book_Author_Authorid]
GO
ALTER TABLE [dbo].[Book]  WITH CHECK ADD  CONSTRAINT [FK_Book_Category_Categoryid] FOREIGN KEY([Categoryid])
REFERENCES [dbo].[Category] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Book] CHECK CONSTRAINT [FK_Book_Category_Categoryid]
GO
USE [master]
GO
ALTER DATABASE [DbLibrary] SET  READ_WRITE 
GO
